// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType";
import type { AccountPoolAvailability } from "./AccountPoolAvailability";
import type { AccountPoolRateLimits } from "./AccountPoolRateLimits";

export type AccountPoolAccount = { profileId: string, label: string | null, priority: number, isActive: boolean, availability: AccountPoolAvailability, planType: PlanType | null, email: string | null, rateLimits: AccountPoolRateLimits, };
