// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountPoolAvailability = { "type": "available" } | { "type": "exhausted", resets_at: number | null, } | { "type": "authenticationUnavailable", reason: string, } | { "type": "disabled" };
