// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolWindowWarmupOutcome } from "./AccountPoolWindowWarmupOutcome";
import type { AccountPoolWindowWarmupPhase } from "./AccountPoolWindowWarmupPhase";

export type AccountPoolWindowWarmup = { outcome: AccountPoolWindowWarmupOutcome,
/**
 * Additive attempt phase; legacy clients can continue reading `outcome`.
 */
phase: AccountPoolWindowWarmupPhase | null, consecutiveFailures: number | null, attemptedAt: number, retryAfter: number | null, };
