// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { PlanType } from "../PlanType";
import type { AccountPoolReadResponse } from "./AccountPoolReadResponse";

export type AccountUpdatedNotification = { authMode: AuthMode | null, planType: PlanType | null,
/**
 * Full native account-pool snapshot when `[account_pool]` is configured.
 *
 * Stable remote clients (including mobile) can render multi-profile status from this
 * notification without calling experimental `accountPool/read`.
 */
accountPool: AccountPoolReadResponse | null, };
