// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountPoolWarmupDebugAccount = { profileId: string, email: string | null, label: string | null, priority: number, isActive: boolean, isCandidate: boolean, availability: string, primaryUsedPercent: number | null, persistedWarmupOutcome: string | null, };
