// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolAccount } from "./AccountPoolAccount";

/**
 * Pushed whenever the account pool's scheduling state changes (active account, availability,
 * or observed rate limits). Unlike `accountPool/read`, the per-account `planType`/`email`
 * identity fields are omitted (`null`) to keep the notification cheap; fetch them on demand.
 */
export type AccountPoolUpdatedNotification = { activeProfileId: string | null, activeGeneration: number | null, accounts: Array<AccountPoolAccount>, };
