// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolWindowWarmupOutcome } from "./AccountPoolWindowWarmupOutcome";

export type AccountPoolWindowWarmup = { outcome: AccountPoolWindowWarmupOutcome, attemptedAt: number, retryAfter: number | null, };
