// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolRateLimitWindow } from "./AccountPoolRateLimitWindow";

export type AccountPoolRateLimits = { primary: AccountPoolRateLimitWindow | null, secondary: AccountPoolRateLimitWindow | null, observedAt: number | null, };
