// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes an ongoing or completed-but-unconfirmed attempt from a request failure.
 */
export type AccountPoolWindowWarmupPhase = "inProgress" | "unconfirmed";
