// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumeAccountRateLimitResetCreditParams = {
/**
 * Expected execution-seat binding captured from the usage read shown for confirmation.
 */
expectedOwnerKey?: string | null,
/**
 * Identifies one logical reset attempt. A UUID is recommended; reuse the same value when
 * retrying that attempt.
 */
idempotencyKey: string,
/**
 * Opaque reset-credit identifier to redeem. When omitted, the host selects the earliest
 * expiring eligible credit, or preserves the original credit for a known retry.
 */
creditId?: string | null, };
