// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { AccountPoolReadResponse } from "./AccountPoolReadResponse";

export type GetAccountResponse = { account: Account | null, requiresOpenaiAuth: boolean,
/**
 * Native multi-account pool snapshot when `[account_pool]` is configured.
 *
 * Stable clients (including mobile) can use this field from `account/read` instead of the
 * experimental `accountPool/read` RPC to show per-profile availability and cooldowns.
 */
accountPool: AccountPoolReadResponse | null, };
