// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { PendingAccountRateLimitResetCredit } from "./PendingAccountRateLimitResetCredit";
import type { RateLimitResetCreditsSummary } from "./RateLimitResetCreditsSummary";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type GetAccountRateLimitsResponse = {
/**
 * Opaque binding to the exact execution seat that supplied this usage read.
 * Clients must preserve it when confirming a reset; a missing key cannot authorize spending.
 */
resetOwnerKey: string | null,
/**
 * An unresolved reset for this seat. Reuse its immutable request and credit identifiers.
 */
pendingResetCredit: PendingAccountRateLimitResetCredit | null,
/**
 * Backend permission for ordinary included usage, validated against the active account.
 * Null means unavailable; clients must not infer recovery from percentages or reset times.
 */
ordinaryUsageAllowed: boolean | null,
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rateLimits: RateLimitSnapshot,
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, rateLimitResetCredits: RateLimitResetCreditsSummary | null,
/**
 * Account associated with this usage snapshot, when supplied by the backend.
 */
accountId: string | null,
/**
 * Optional backend-owned banner from the same usage read. Its nested keys retain the
 * backend's snake_case contract; an absent banner leaves the client's existing UI unchanged.
 */
rateLimitUpsell: JsonValue | null, };
