// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nonsecret recovery metadata for one unresolved, owner-bound reset operation.
 */
export type PendingAccountRateLimitResetCredit = { ownerKey: string, idempotencyKey: string, creditId: string | null, };
