const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const vm = require('node:vm');
const context = vm.createContext({ window: {} });
vm.runInContext(readFileSync(join(__dirname, 'webui/reset-operations.js'), 'utf8'), context);
const { create } = context.window.AccountManagerResetOperations;
const operation = (owner, key) => ({ profileId: `profile-${owner}`, ownerKey: owner.repeat(64), idempotencyKey: key, creditId: `credit-${owner}`, startedAt: 1 });
const values = new Map();
const storage = { getItem: key => values.get(key) || null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) };
let resets = create(storage, 'resets');
resets.put(operation('a', 'original-a'));
resets.put(operation('b', 'original-b'));
resets = create(storage, 'resets');
assert.deepEqual(JSON.parse(JSON.stringify(resets.all())), [operation('a', 'original-a'), operation('b', 'original-b')]);
assert.throws(() => resets.put(operation('a', 'replacement-a')), /already retained/);
resets.recover(operation('a', 'server-original-a'));
assert.equal(resets.current('profile-a', 'a'.repeat(64), 'server-original-a').idempotencyKey, 'server-original-a');
assert.equal(resets.current('profile-a', 'a'.repeat(64), 'original-a').idempotencyKey, 'original-a');
resets.remove(operation('a', 'server-original-a'));
assert.throws(() => resets.put({ ...operation('b', 'original-a') }), /already retained/);
resets.remove(operation('b', 'original-b'));
assert.deepEqual(JSON.parse(JSON.stringify(resets.all())), [operation('a', 'original-a')]);
const legacy = operation('b', 'legacy-b');
delete legacy.ownerKey;
storage.setItem('legacy', JSON.stringify(legacy));
resets = create(storage, 'legacy');
assert.equal(resets.current(legacy.profileId, 'b'.repeat(64)).idempotencyKey, 'legacy-b');
assert.throws(() => resets.put(operation('b', 'new-b')), /already retained/);
resets.put(operation('b', 'legacy-b'));
assert.equal(JSON.parse(storage.getItem('legacy')).version, 2);
assert.deepEqual(JSON.parse(JSON.stringify(resets.all())), [operation('b', 'legacy-b')]);
for (const invalid of [false, {version:9,operations:[]}, {...operation('a','invalid'),ownerKey:'wrong'}, {...operation('a','invalid'),ownerKey:['a'.repeat(64)]}, {version:2,operations:[operation('a','duplicate'),operation('b','duplicate')]}]) {
  storage.setItem('invalid', JSON.stringify(invalid));
  const before = storage.getItem('invalid');
  resets = create(storage, 'invalid');
  assert.equal(resets.problem, true);
  assert.throws(() => resets.put(operation('c','new')), /could not be verified/);
  assert.equal(storage.getItem('invalid'), before);
}
const records = Array.from({length:64}, (_, index) => ({...operation('a',`key-${index}`),ownerKey:index.toString(16).padStart(64,'0')}));
storage.setItem('full', JSON.stringify({version:2,operations:records}));
resets = create(storage, 'full');
assert.equal(resets.problem, false);
assert.throws(() => resets.put(operation('f','overflow')), /64 reset operations/);
console.log('Reset operation collection: original binding, restart, migration, malformed storage and capacity passed');
